/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JoseDiaz (https://sketchfab.com/JoseDiaz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/robot-1-57651698b1974ea39f7004b2366c3a38
Title: Robot 1
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3d/robot_1.glb'
import { a } from '@react-spring/three'

const Robot = ({ currentAnimation, ...props }) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop())
        if (actions[currentAnimation]) actions[currentAnimation].play()
    }, [actions, currentAnimation])

    return (
        <a.group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                >
                    <group name="fbx_mergefbx" rotation={[-Math.PI, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Object_4">
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.Robot_1}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <group name="Object_6" />
                                    <group name="Robot_1_Mesh" />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </a.group>
    )
}

export default Robot
