/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shayan (https://sketchfab.com/mshayan02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ekana-stadium-low-poly-lucknow-city-game-asset-d088ff7bbb0a477ab6dd492865d38f3b
Title: Ekana Stadium Low Poly Lucknow City game asset
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import stadiumScene from '../assets/3d/stadium.glb'
import { a } from '@react-spring/three'

const Stadium = (props) => {
    const stadiumRef = useRef()

    const { nodes, materials } = useGLTF(stadiumScene)
    return (
        <a.group ref={stadiumRef}{...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={29.067}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <mesh
                        geometry={nodes.Ekana_Stadium_Ekana_Stadium_0.geometry}
                        material={materials.Ekana_Stadium}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                </group>
            </group>
        </a.group>
    )
}

export default Stadium